PodveziSosedaSource/app/Passenger/controllers.py
from flask import Blueprint, render_template, redirect,request, session, flash, make_response, url_for
from flask_login import login_required, current_user
import json

from datetime import date, timedelta, datetime

from app.models import db, Users, Profiles, Trips
from app.utils.utils import confirm_required
from app.utils.geoloc import get_geocode_osm, gd_distance
from .alchemyToJSON import AlchemyEncoder


passenger = Blueprint('passenger', __name__, url_prefix ='/join')


@passenger.route("/", methods=["GET", "POST"])
@confirm_required
@login_required
def join():
    '''Страница пассажира'''
    # Пагинация (бесконечный скролл)
    POSTS_ON_PAGE = 3

    trips = Trips.query.filter(Trips.driver_id!=current_user.get_id(), Trips.trip_date>=datetime.now().date()).order_by(Trips.trip_date).all()

    # Проверка поездок на близость к дому точки выезда или точки приезда
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
    home_lati = profile.home_latitude
    home_long = profile.home_longitude

    # В каком радиусе искать поездки (км)
    TRIP_RADIUS = profile.trip_search_radius

    valid_trips = []
    for trp in trips:
        driver = Users.query.filter(Users.id==trp.driver_id).first()
        drvr_prfl = Profiles.query.filter(Users.id==trp.driver_id).first()
        if gd_distance( (trp.from_latitude, trp.from_longitude ), (home_lati, home_long) ) <= TRIP_RADIUS or \
            gd_distance( (trp.to_latitude, trp.to_longitude ), (home_lati, home_long) ) <= TRIP_RADIUS:
                vtrip = {
                    "trip_id": trp.trip_id,
                    "driver_id": trp.driver_id,
                    "driver_name": f"{driver.first_name}", #{driver.second_name}",
                    "trip_type": "домой" if (drvr_prfl.home_latitude == trp.to_latitude and drvr_prfl.home_longitude == trp.to_longitude) else "в город",
                    "day": ["Сегодня", "Завтра", "Послезавтра"][trp.trip_date.day-datetime.now().date().day],
                    "time": trp.trip_time.strftime("%H:%M"),
                    "from": trp.from_address,
                    "to": trp.to_address,
                    "passengers": {
                        id: Users.query.filter(Users.id==id).first().first_name for id in trp.passengers_ids
                    },
                    "description": trp.description,
                    "joined": int(current_user.get_id()) in trp.passengers_ids
                }
                valid_trips.append(vtrip)

    if request.method == "POST":
        req = request.get_json()
        total_pages = len(valid_trips) // POSTS_ON_PAGE + 1
        resp = make_response(json.dumps({ "trips": valid_trips[POSTS_ON_PAGE*req['next_page']-POSTS_ON_PAGE+1:POSTS_ON_PAGE*req['next_page']], 
                                          "pages": total_pages }, cls=AlchemyEncoder))
        print(valid_trips[POSTS_ON_PAGE*req['next_page']-POSTS_ON_PAGE+1:POSTS_ON_PAGE*req['next_page']])                            
        return resp

    return render_template("Passenger/join.html", trips=valid_trips) # trips=valid_trips[0:POSTS_ON_PAGE]


@passenger.route("/<trip_id>", methods=["GET", "POST"])
@login_required
def join_trip(trip_id):
    '''Присоединение к поездке'''
    trip = Trips.query.filter(Trips.trip_id==trip_id).first()
    if int(current_user.get_id()) in trip.passengers_ids:
        flash("Вы уже присоединились к этой поездке ранее", "error")
    elif len(trip.passengers_ids) >= trip.max_passengers_amount:
        flash("К поездке уже присоединилось максимальное количество пассажиров", "error")
    else:
        try:
            trip.passengers_ids = [*trip.passengers_ids, current_user.get_id()]
            flash("Вы успешно присоединились к поездке", "success")
            db.session.flush()
            db.session.commit()
        except:
            flash("Произошла ошибка", "error")
            db.session.rollback()
    return redirect(url_for("passenger.join"))


@passenger.route("/discard/<trip_id>", methods=["GET", "POST"])
@login_required
def discard_trip(trip_id):
    '''Отказ от участия в поездке'''
    trip = Trips.query.filter(Trips.trip_id==trip_id).first()
    if int(current_user.get_id()) not in trip.passengers_ids:
        flash("Вы не присоединялись к этой поездке", "error")
    else:
        try:
            trip.passengers_ids = [int(i) for i in trip.passengers_ids if i != int(current_user.get_id())]
            flash("Вы успешно исключены из участников поездки", "success")
            db.session.flush()
            db.session.commit()
        except:
            flash("Произошла ошибка", "error")
            db.session.rollback()
    return redirect(url_for("passenger.join"))

PodveziSosedaSource/app/Profile/controllers.py
from flask import Blueprint, render_template, url_for, make_response, current_app
from flask_login import login_required, current_user

from app.models import Users, Profiles
from app.utils.utils import confirm_required


profiles = Blueprint('profiles', __name__, url_prefix ='/profile')


# Профиль вошедшего пользователя

@profiles.route("/", methods=["POST", "GET"])
@confirm_required
@login_required
def profile():
    '''Профиль пользователя'''
    user = Users.query.filter(Users.id == current_user.get_id()).first()
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
    return render_template("Profile/profile.html", id=current_user.get_id(), name =f"{user.first_name} {user.second_name}", description=profile.description, email=user.email, 
        phone=user.phoneNum, confirmed=user.confirmed, address=profile.home_address)


@profiles.route('/load_avatar')
@login_required
def load_avatar():
    '''Выгрузка аватара из бд'''
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()

    img = None
    if not profile.photo:
        try:
            with current_app.open_resource(current_app.root_path + url_for('static', filename='imgs/default-ava.png'), "rb") as f:
                img = f.read()
        except FileNotFoundError as e:
                print("Не найден аватар по умолчанию: "+str(e))
    else:
        img = profile.photo

    if not img:
        return ""
    h = make_response(img)
    return h


# Профили остальных пользователей

@profiles.route("/<user_id>")
@login_required
def user(user_id):
    '''Профиль внешнего пользователя'''
    user = Users.query.filter(Users.id == user_id).first_or_404()
    profile = Profiles.query.filter(Profiles.user_id == user_id).first_or_404()
    return render_template("Profile/user.html", id=user_id, name =f"{user.first_name} {user.second_name}", description=profile.description, email=user.email, 
        phone=user.phoneNum, confirmed=user.confirmed, address=profile.home_address)


@profiles.route('/load_user_avatar/<user_id>')
@login_required
def load_user_avatar(user_id):
    '''Выгрузка аватара из бд'''
    profile = Profiles.query.filter(Profiles.user_id == user_id).first_or_404()

    img = None
    if not profile.photo:
        try:
            with current_app.open_resource(current_app.root_path + url_for('static', filename='imgs/default-ava.png'), "rb") as f:
                img = f.read()
        except FileNotFoundError as e:
                print("Не найден аватар по умолчанию: "+str(e))
    else:
        img = profile.photo

    if not img:
        return ""
    h = make_response(img)
    return h

PodveziSosedaSource/app/templates/Passenger/join.html
{% extends 'base.html' %}

{% block css_style %}
    <link href="{{ url_for('static', filename='css/passenger.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% for cat, msg in get_flashed_messages(True) %}
        <div id="toastDiv" class="position-fixed top-30 start-50 translate-middle-x p-3" style="z-index: 12">
        <div id="infoToast" class="toast hide text-white {{cat}} border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
            <strong class="me-auto">Информация</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
            {{msg}}
            </div>
        </div>
        </div>
    {% endfor %}

    <div class="p-2">
        <h1>Поездки рядом с вами:</h1>

        {% if trips %}
            <div id="trips_list">
                {% for trip in trips %}
                    <div class="trip" style="max-width: 1000px;">
                        <div class="border rounded mt-3 shadow-sm">
                            <div class="head rounded text-muted p-2 pb-2" style="background-color: rgb(232, 249, 255);">
                                <span class="text-dark" style="font-size: 22px;"><a href="{{ url_for('profiles.user', user_id=trip['driver_id']) }}" class="text-link text-decoration-none">{{ trip["driver_name"] }}</a> <span class="trip_type">едет {{ trip["trip_type"] }}</span> </span>
                                <span class="text-dark" style="float: right; font-size: 22px;">{{ trip["day"] }} {{ trip["time"] }}</span>
                            </div>
                            <div class="mx-1 p-2">
                                <p><b>Откуда: </b>{{ trip["from"] }}</p>
                                <p><b>Куда: </b>{{ trip["to"] }}</p>
                                <span><b>Пассажиры:</b>
                                    <!-- <a href="">первый</a>, <a href="">второй</a> -->
                                    {% if trip["passengers"]|length != 0 %}
                                        {% for id, name in trip["passengers"].items() %}
                                            <a href="{{ url_for('profiles.user' ,user_id=id) }}" class="rounded mx-1 px-1 link" style="background-color: rgb(232, 249, 255);text-decoration: none;">{{ name }}</a> 
                                        {% endfor %}
                                    {% else %}
                                        <span class="text-muted">станьте первым пассажиром</span>
                                    {% endif %}
                                </span>
                                <p class="text-secondary" style="max-width: 700px;">
                                    {{ trip["description"] }}
                                </p>
                                <div class="text-end">
                                    {% if trip["joined"] %}
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#ModalN{{ trip['trip_id'] }}">
                                            <i class="material-icons but-icon">done</i>Вы присоединились
                                        </button>
                                        
                                        <!-- Modal -->
                                        <div class="modal fade" id="ModalN{{ trip['trip_id'] }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Выполните действие</h5>
                                                </div>
                                                <div class="modal-body">
                                                    Отказаться от поездки?
                                                </div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                                                <a href="{{ url_for('passenger.discard_trip', trip_id = trip['trip_id']) }}" class="btn btn-danger mx-2 shadow-none pbutton">Отказаться от поездки</a>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
  
                                    {% else %}
                                        <a href="{{ url_for('passenger.join_trip', trip_id = trip['trip_id']) }}" class="btn btn-primary mx-2 shadow-none pbutton"> <i class="material-icons but-icon">waving_hand</i>Присоединиться</a>
                                    {% endif %}
                                </div>
                                
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- <div style="max-width: 1000px;">
                <div class="text-center mt-5">
                    <button id="lmbtn" class="btn btn-secondary shadow-none btn-lg" onclick="load_more()">
                        <span id="spinner" class="spinner-border spinner-border-sm" role="status" aria-hidden="true" hidden></span>
                        <span class="sr-only">Загрузить еще</span>
                    </button>
                    <p id = "endhistory" class="text-muted mt-3 mb-3" hidden>Это все ваши поездки</p>
                </div>
            </div> -->
        {% else %}
            <h3 class="text-muted mt-3 mb-3">Нет поездок рядом</h3>
        {% endif %}
        <br class="mb-5"/><br class="mb-5"/><br>
    </div>

{% endblock %}

{% block script %}
    <!-- Бесконечный скролл -->
    <!-- <script>
        let page_status = {
            next_page: 2
        }

        async function load_more() {
            spin = document.getElementById("spinner");
            spin.removeAttribute("hidden")
            load_button = document.getElementById("lmbtn")
            load_button.setAttribute("disabled", true);
            
            let response = await fetch('{{ url_for("passenger.join") }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json;charset=utf-8'
            },
            body: JSON.stringify(page_status)
            });
            
            page_status["next_page"]++;

            let result = await response.json();

            spin.setAttribute("hidden", true);
            load_button.removeAttribute("disabled");

            for (let i=0; i < result["trips"].length; i++) {
                trip = result["trips"][i]

                var div = document.createElement('div');
                div.className = "trip mt-4";

                if (trip["description"]) var description = trip['description']
                else var description = "Описание отсутсвует"

                div.innerHTML = `
                <div class="trip" style="max-width: 1000px;">
                    <div class="border rounded mt-3 shadow-sm">
                        <div class="head rounded text-muted p-2 pb-2" style="background-color: rgb(232, 249, 255);">
                            <span class="text-dark" style="font-size: 22px;"><a href="/profile/${trip['driver_id']}" class="text-link text-decoration-none">${trip["driver_name"]}</a> <span class="trip_type">едет ${trip["trip_type"]}</span> </span>
                            <span class="text-dark" style="float: right; font-size: 22px;">${ trip["day"] } ${ trip["time"] }</span>
                        </div>
                        <div class="mx-1 p-2">
                            <p><b>Откуда: </b>${ trip["from"] }</p>
                            <p><b>Куда: </b>${ trip["to"] }</p>
                            <span><b>Пассажиры:</b>

                            </span>
                            <p class="text-secondary" style="max-width: 700px;">
                                ${trip["description"]}
                            </p>
                            <div class="text-end">
                                <a href="${ url_for('passenger.join_trip', trip_id = trip['trip_id']) }" class="btn btn-primary mx-2 shadow-none pbutton">Подвези!</a>
                            </div>
                            
                        </div>
                    </div>
                </div>`;

                document.getElementById("trips_list").appendChild(div)
            }

            if (page_status["next_page"]==result["pages"] + 1) {
                load_button.setAttribute("hidden", true);
                document.getElementById("endhistory").removeAttribute("hidden")
            }

        }
    </script> -->

    <!-- Блок скрипта для выделения иконки в меню -->
    <script>    
        var link = document.getElementById("join_link");
        link.classList.add("nav__link--active");
    </script>

    <!-- Тост -->
    <script>
        var option = {
            animation: true,
            delay: 3000
        }
        function showToast() {
            let toastAlert = document.getElementById("infoToast")
            let bsAlert = new bootstrap.Toast(toastAlert, option)
            bsAlert.show()
        }
        window.onload = showToast()
    </script>
    
    <script>
    // При большом экране изменим раположени тоста
    if (window.innerWidth >= 767) {
        var toastCont = document.getElementById("toastDiv")
        toastCont.classList.remove("start-50", "translate-middle-x")
        toastCont.classList.add("end-0")
    }
    </script>
{% endblock %}