PodveziSosedaSource/app/Driver/controllers.py
from flask import Blueprint, render_template, redirect,request, session, flash, make_response, url_for
from flask_login import login_required, current_user
import json

from datetime import date, timedelta, datetime

from app.models import db, Users, Profiles, Trips
from app.utils.utils import confirm_required
from app.utils.geoloc import get_geocode_osm, gd_distance
from .alchemyToJSON import AlchemyEncoder

driver = Blueprint('driver', __name__, url_prefix ='/drive')


@driver.route('/')
@confirm_required
@login_required
def drive():
    '''Страница водителя'''
    first_2_actual_trips = Trips.query.filter(Trips.driver_id == current_user.get_id(), Trips.trip_date>=datetime.now().date()) \
                                .order_by(Trips.trip_date).limit(2).all()
    days_possible=["Сегодня", "Завтра", "Послезавтра"]
    days=[days_possible[first_2_actual_trips[i].trip_date.day-datetime.now().date().day] for i in range(len(first_2_actual_trips))]

    last_2_in_history = Trips.query.filter(Trips.driver_id == current_user.get_id(), Trips.trip_date<datetime.now().date()) \
                                .order_by(Trips.trip_date.desc()).limit(2).all()

    return render_template("Driver/driver.html", trips=first_2_actual_trips, days=days, history=last_2_in_history)


@driver.route('/setup', methods=["GET", "POST"])
@confirm_required
@login_required
def setup_drive():
    '''Страница для создания новой поездки'''
    # Проверка заполненности профиля у пользователя
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
    if not profile.home_address:
        flash("Вы не указали домашний адрес в профиле", "error")
        return redirect(url_for("driver.drive"))

    # Создание переменных в сессии, в которых будет хранится информация из формы
    session_strings = ["address", "rawTime"]
    session_ints = ["radioChecked", "tripDayNum", "passengersValue"]
    for svalue in session_strings:   
        if svalue not in session:   
            session[svalue]=""
    for svalue in session_ints:
        if svalue not in session:
            session[svalue] = 0

    # Обработка формы
    if request.method == "POST":

        # Получение данных из формы
        trip_type = int(request.form["tripType"])
        address = get_geocode_osm(request.form["addressAuto"])
        day_delta = int(request.form["day"])-1 # Через сколько дней будет поездка
        time_raw = request.form["timeRaw"]
        passengers = int(request.form["passengersNum"])
        description = request.form["tripDescription"]

        # Преобразование данных
        profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()

        if trip_type == 1:
            # Домой
            address_from = address.address
            address_to = profile.home_address # Домашний адрес, указанный в профиле пользователя
            from_lati = address.latitude
            from_long = address.longitude
            to_lati = profile.home_latitude
            to_long = profile.home_longitude
        else:
            # В город
            address_from = profile.home_address # Домашний адрес, указанный в профиле пользователя
            address_to = address.address
            from_lati = profile.home_latitude
            from_long = profile.home_longitude
            to_lati = address.latitude
            to_long = address.longitude
        
        trip_date = date.today() + timedelta(days=day_delta)
        trip_datetime = datetime.strptime(f'{trip_date.day}/{trip_date.month}/{trip_date.year} {time_raw}', r'%d/%m/%Y %H:%M')
        trip_time = trip_datetime.time()
        passengers_number = passengers

        #print(f'Создана новая поездка \nОткуда: {address_from}\nКуда: {address_to}\nДата поездки: {trip_date}\nВремя поездки: {trip_datetime}\nМаксимальное число пассажиров: {passengers_number}')

        # Проверка, не насоздавал ли пользователь слишком много поездок
        look_for_trips = Trips.query.filter(Trips.trip_date==trip_date, Trips.driver_id==current_user.get_id()).all()
        #look_for_trips = Trips.query.filter( Trips.driver_id==current_user.get_id()).all()
        if len(look_for_trips) > 2:
            flash("Запрещено создавать больше трех поездок на один день", "error")
            return redirect(url_for("driver.drive"))

        # Проверка этой новой поездки на схожесть с уже существующими
        same_date_trips = Trips.query.filter(Trips.trip_date==trip_date).all()
        for trp in same_date_trips:
            if gd_distance( (trp.from_latitude, trp.from_longitude ), (from_lati, from_long) ) < 0.6 and \
               gd_distance( (trp.to_latitude, trp.to_longitude ), (to_lati, to_long) ) < 0.6 and \
               trp.trip_time.hour==trip_time.hour and \
               abs(trp.trip_time.minute-trip_time.minute) < 30:

                driver = Users.query.filter(Users.id==trp.driver_id).first()
                if driver: 
                    driver_name = driver.first_name+" "+driver.second_name
                    driver_link = url_for("profiles.user", user_id=driver.id)

                session["rawTime"]=time_raw
                session["tripDescription"]=description
                return render_template("Driver/similar.html",
                                      from_where=trp.from_address, 
                                      to_where=trp.to_address,
                                      date=trp.trip_date, 
                                      time=f'{trp.trip_time.hour}:{trp.trip_time.minute}', 
                                      driver_link=driver_link, 
                                      driver_name=driver_name)

        # Запись в бд
        try:
            trips = Trips(driver_id=current_user.get_id(), 
                          max_passengers_amount=passengers_number,
                          from_address=address_from,
                          from_latitude=from_lati,
                          from_longitude=from_long,
                          to_address=address_to,
                          to_latitude=to_lati,
                          to_longitude=to_long,
                          trip_date=trip_date,
                          trip_time=trip_time,
                          description=description)
            db.session.add(trips)
            db.session.flush()
            db.session.commit()

            flash("Поездка успешно создана", "success")

            # Обнуление сессии
            session["radioChecked"] = 0
            session["address"] = ""
            session["tripDayNum"] = 0
            session["rawTime"] = ""
            session["passengersValue"] = 0

        except Exception as exc:
            print(exc)
            db.session.rollback()
            flash('Не удалось создать поездку', category = 'error')
            print("Ошибка добавления поездки в бд")

        return redirect(url_for("driver.drive"))

    return render_template("Driver/setup.html")


@driver.route("/maps")
@confirm_required
@login_required
def maps():
    '''Страница с картой'''
    return render_template("Driver/maps.html")


@driver.route("/get_address_from_map", methods=["GET"])
@confirm_required
@login_required
def get_address_from_map():
    '''Сохраняет полученный адрес в сессии'''
    if request.method == "GET":
        session["address"] = request.args.get("address")
    return session["address"]


@driver.route("/get_form_input", methods=["GET"])
@confirm_required
@login_required
def get_form_input():
    '''Возвращает сохраненные данные из формы в виде json'''
    fields = {"address": session["address"],
              "radioChecked": session["radioChecked"],
              "tripDayNum": session["tripDayNum"],
              "rawTime": session["rawTime"],
              "passengersValue": session["passengersValue"]}
    return fields


@driver.route("/safe_form_input", methods=["GET"])
@confirm_required
@login_required
def safe_form_input():
    '''Сохраняет данные из формы в сессии'''
    session["radioChecked"] = int(request.args.get("triptype"))-1
    session["address"] = request.args.get("address") 
    session["tripDayNum"] = int(request.args.get("tripday"))-1
    session["rawTime"] = request.args.get("timeinput")
    session["passengersValue"] = int(request.args.get("passengers"))-1
    return "ok"


# Создание поездки, даже если уже есть похожая
@driver.route("/force", methods=["GET"])
@confirm_required
@login_required
def create_trip_by_force():
    # Получение данных, сохраненных в сессии
    trip_type = int(session["radioChecked"])
    address = get_geocode_osm(session["address"])
    day_delta = int(session["tripDayNum"]) # Через сколько дней будет поездка
    time_raw = session["rawTime"]
    passengers = int(session["passengersValue"])
    description = session["tripDescription"]

    # Преобразование данных

    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()

    if trip_type == 1 or trip_type == 0:
        # Домой
        address_from = address.address
        address_to = profile.home_address # Домашний адрес, указанный в профиле пользователя
        from_lati = address.latitude
        from_long = address.longitude
        to_lati = profile.home_latitude
        to_long = profile.home_longitude
    else:
        # В город
        address_from = profile.home_address # Домашний адрес, указанный в профиле пользователя
        address_to = address.address
        from_lati = profile.home_latitude
        from_long = profile.home_longitude
        to_lati = address.latitude
        to_long = address.longitude
    
    trip_date = date.today() + timedelta(days=day_delta)

PodveziSosedaSource/app/templates/Driver/driver.html
{% extends 'base.html' %}

{% block css_style %}
<link href="{{ url_for('static', filename='css/driver.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% for cat, msg in get_flashed_messages(True) %}
    <!-- <div class="flash {{cat}}">{{msg}}</div> -->

    <div id="toastDiv" class="position-fixed top-30 start-50 translate-middle-x p-3" style="z-index: 12">
    <div id="infoToast" class="toast hide text-white {{cat}} border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
        <strong class="me-auto">Информация</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
        {{msg}}
        </div>
    </div>
    </div>
    {% endfor %}

    <h1>Водитель</h1>

	<a href="{{ url_for('driver.setup_drive') }}" class="btn btn-md btn-primary create-trip shadow-none">Создать поездку</a>
    
    <div class="content">
        <div class="blocks">
            <div class="active-trips p-3">
                <h3 class="">Активные поездки:</h3>

                <!-- <div class="border rounded bg-light mt-2">
                    <div class="head rounded text-muted p-1">
                        <a href="#" class="text-muted text-decoration-none">Имя фамилия</a>
                        <span class="text-dark" style="float: right;">Завтра 00:00</span>
                    </div>
                    <div class="mx-1">
                        <p><b>Откуда: </b>адрес</p>
                        <p><b>Куда: </b>адрес</p>
                        <a href="" class="btn btn-secondary btn-sm mx-2 shadow-none" style="float: right;">Подробнее</a>
                        <p class="text-secondary">Это описание это описание</p>
                    </div>
                </div> -->
                {% if trips %}
                    {% for i in range(trips|length) %}
                        <div class="border rounded bg-light mt-3 shadow-sm">
                            <div class="head rounded text-muted p-1">
                                <a href="#" class="text-dark text-decoration-none">Поездка</a>
                                <span class="text-dark" style="float: right;">{{ days[i] }} {{ trips[i].trip_time.strftime("%H:%M") }}</span>
                            </div>
                            <div class="mx-1">
                                <p><b>Откуда: </b>{{ trips[i].from_address }}</p>
                                <p><b>Куда: </b>{{ trips[i].to_address }}</p>
                                <a href="{{ url_for('driver.trip', trip_id=trips[i].trip_id) }}" class="btn btn-secondary btn-sm mx-2 shadow-none" style="float: right;">Подробнее</a>
                                <p class="text-secondary">
                                    {% if trips[i].description %}
                                        {{ trips[i].description }}
                                    {% else %}
                                        Описание отсутсвует
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="text-center">
                       <a href="{{ url_for('driver.active_trips') }}" class="btn btn-primary shadow-none mt-3"> <i class="material-icons but-icon">keyboard_double_arrow_down</i>  Посмотреть все</a>
                    </div>
                {% else %}
                    <p class="text-muted mt-3">Нет активных поездок</p>
                {% endif %}
            </div>

            <div class="history p-3">
                <h3 class="">История поездок:</h3>

                {% if history %}
                {% for i in range(history|length) %}
                    <div class="border rounded bg-light mt-3 shadow-sm">
                        <div class="head rounded text-muted p-1">
                            <a href="#" class="text-dark text-decoration-none">Поездка</a>
                            <span class="text-dark" style="float: right;">{{ history[i].trip_date.strftime("%d.%m.%Y") }} {{ history[i].trip_time.strftime("%H:%M") }}</span>
                        </div>
                        <div class="mx-1">
                            <p><b>Откуда: </b>{{ history[i].from_address }}</p>
                            <p><b>Куда: </b>{{ history[i].to_address }}</p>
                            <a href="{{ url_for('driver.trip', trip_id=history[i].trip_id) }}" class="btn btn-secondary btn-sm mx-2 shadow-none" style="float: right;">Подробнее</a>
                            <p class="text-secondary">
                                {% if history[i].description %}
                                    {{ history[i].description }}
                                {% else %}
                                    Описание отсутсвует
                                {% endif %}
                            </p>
                        </div>
                    </div>
                {% endfor %}
                <div class="text-center">
                    <a href="{{ url_for('driver.history') }}" class="btn btn-primary shadow-none mt-3">  <i class="material-icons but-icon" >keyboard_double_arrow_down  </i>  Посмотреть все</a>
                </div>
                {% else %}
                    <p class="text-muted mt-3">Нет истории</p>
                {% endif %}
            </div>
        </div>
        <!--<div class="statistic p-3">
            <h3 class="">Cтатистика:</h3>
            <p class="">Совершено поездок: </p>
            <p class="">Людей перевезено: </p>
        </div> -->
    </div>
{% endblock %}

{% block script %}
    <!-- Блок скрипта для выделения иконки в меню -->
    <script>    
        var link = document.getElementById("drive_link");
        link.classList.add("nav__link--active");
    </script>

    <!-- Тост -->
    <script>
        var option = {
            animation: true,
            delay: 3000
        }
        function showToast() {
            let toastAlert = document.getElementById("infoToast")
            let bsAlert = new bootstrap.Toast(toastAlert, option)
            bsAlert.show()
        }
        window.onload = showToast()
    </script>
    
    <script>
    // При большом экране изменим раположени тоста
    if (window.innerWidth >= 767) {
        var toastCont = document.getElementById("toastDiv")
        toastCont.classList.remove("start-50", "translate-middle-x")
        toastCont.classList.add("end-0")
    }
    </script>
{% endblock %}

PodveziSosedaSource/app/templates/Driver/maps.html
<!DOCTYPE html>
<html>
  <head>
    <title>Выбрать адрес на карте</title>

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no initial-scale=1, maximum-scale=1"
    />

    <link rel="manifest" href="{{ url_for('static', filename='pwa/manifest.json') }}"> <!--Манифест для работы PWA приложения-->

    <link rel="stylesheet" href="https://unpkg.com/leaflet@latest/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> Гугл шрифт-иконки -->

    <script src="https://unpkg.com/leaflet@latest/dist/leaflet-src.js"></script>
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
    <style type="text/css">
      @font-face {
        font-family: 'Material Icons';
        font-style: normal;
        font-weight: 400;
        src: url(https://example.com/MaterialIcons-Regular.eot); 
        src: local('Material Icons'),
          local('MaterialIcons-Regular'),
          url(../../static/fonts/MaterialIcons-Regular.woff2) format('woff2'),
          url(../../static/fonts/MaterialIcons-Regular.ttf) format('truetype');
      }

      .material-icons {
        font-family: 'Material Icons';
        font-weight: normal;
        font-style: normal;
        font-size: 24px;
        display: inline-block;
        line-height: 1;
        text-transform: none;
        letter-spacing: normal;
        word-wrap: normal;
        white-space: nowrap;
        direction: ltr;

        /* Support for all WebKit browsers. */
        -webkit-font-smoothing: antialiased;
        /* Support for Safari and Chrome. */
        text-rendering: optimizeLegibility;
        /* Support for Firefox. */
        -moz-osx-font-smoothing: grayscale;
        /* Support for IE. */
        font-feature-settings: 'liga';
      }

      body {
        margin: 0;
        font-family: sans-serif;
        overflow: hidden;
      }
      #header {
        text-align: center;
        display: flex;
        flex-direction: row;
      }

      #back_btn, #back_btn:hover, #back_btn:active {
        color: black;
        margin-left: 8px;
        margin-top: 3px;
      }

      #back_icon {
        font-size: 30px;
      }

      h3{
          padding: 0;
          margin: 0;
          padding-top: 6px;
          padding-bottom: 6px;
          font-weight:500;
          margin-left: auto;
          margin-right: auto;
          margin-top: 2px;
      }
      #map {
        position: absolute;
        width: 100%;
        height: 100%;
        border-top: 2px solid rgb(167, 167, 167);
      }

      #selectButton {
        border: none; outline: none;
        appearance: none;
        max-width: 100px;
        background-color: rgb(43, 82, 189);
        color: rgb(241, 241, 241);
        font-size: 13px;
        padding: 5px;
        border-radius: 30px;
        margin-top: 4px;
        margin-left: auto;
        margin-right: auto;
        transition-duration: .5s;
        }
        #selectButton:hover {
            font-size: 15px;
            transition-duration: .5s;
        }
        #selectButton:active {
            background-color: rgb(2, 67, 245);
            transition-duration: .5s;
        }
    </style>
  </head>
  <body>
    <div id="header">
      <a id = "back_btn" href="javascript:window.history.back();">
        <div class="nav__cont">
              <i id="back_icon" class="material-icons nav__icon">arrow_back</i>
        </div>
      </a>
      <h3>Нажмите на карту, чтобы выбрать адрес</h3>
    </div>
    <div id="map"></div>
   

    <script type="text/javascript">
      var map = L.map('map').setView([55.748002, 37.624397], 10);

      var geocoder = L.Control.Geocoder.nominatim();
      if (typeof URLSearchParams !== 'undefined' && location.search) {
        var params = new URLSearchParams(location.search);
        var geocoderString = params.get('geocoder');
        if (geocoderString && L.Control.Geocoder[geocoderString]) {
          console.log('Using geocoder', geocoderString);
          geocoder = L.Control.Geocoder[geocoderString]();
        } else if (geocoderString) {
          console.warn('Unsupported geocoder', geocoderString);
        }
      }

      var control = L.Control.geocoder({
        query: 'Москва, улица Солянка',
        placeholder: 'Вводите адрес',
        geocoder: geocoder
      }).addTo(map);
      var marker;

      let classic = "https://{s}.tile.osm.org/{z}/{x}/{y}.png" // Быстро работает
      let humanitarian = "http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png" // Красивее
      L.tileLayer(humanitarian, {
        attribution: '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

      let address; // Здесь хранится адрес, который отправится при нажатии на кнопку
      map.on('click', function(e) {
        geocoder.reverse(e.latlng, map.options.crs.scale(map.getZoom()), function(results) {
          var r = results[0];
          if (r) {
            if (marker) {
              marker
                .setLatLng(r.center)
                .setPopupContent(r.html+"</br><button id='selectButton' onclick='sendAddress()'>Выбрать</button>" || r.name)
                .openPopup();
                console.log("1 "+r.center + r.name)
                address=r.name
            } else {
              marker = L.marker(r.center)
                .bindPopup(r.name +"</br><button id='selectButton' onclick='sendAddress()'>Выбрать</button>")
                .addTo(map)
                .openPopup();
                console.log("2 "+r.center + r.name)
                address=r.name
            }
          }
        });
      });

      function sendAddress() {
        const request = new XMLHttpRequest();
        request.open('GET', `/drive/get_address_from_map?address=`+address, "Тест");
        request.onload = () => {
          window.location.href = "{{ url_for('driver.setup_drive') }}"
        }; 
        request.send();
      }
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='pwa/app.js') }}"></script> <!--Сервис-воркер для PWA-->
  </body>
</html>

PodveziSosedaSource/app/templates/Driver/setup.html
{% extends 'base.html' %}


{% block css_style %}
  <title>Создание поездки</title>
  <link  href="{{ url_for('static', filename='css/picker.css') }}" rel="stylesheet">
  <link  href="{{ url_for('static', filename='css/hints.css') }}" rel="stylesheet">
{% endblock %}


{% block content %}
  <div class="container">
      <div class="row">
        <div class="col">
          <div class="card shadow-sm mt-4 mb-3">
            <div class="card-header bg-transparent">
              <h2>Создание поездки</h2>
            </div>
            <div class="card-body">
              <form action="{{ url_for('driver.setup_drive') }}" method="post" autocomplete="off">
                <div class="container mb-4">
                  <div class="row">
                    <div class="col-md-2"><h5>Тип поездки</h5></div>
                    <div class="col-md-8">
                      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                        <input type="radio" class="btn-check" name="tripType" id="btnradio1" autocomplete="off" value="1" onchange="changeAddressTitle(), safe_form_input()">
                        <label class="btn btn-outline-primary shadow-none" for="btnradio1"><i class="material-icons but-icon">cottage</i>Домой</label>     
                        <input type="radio" class="btn-check" name="tripType" id="btnradio2" autocomplete="off" value="2" onchange="changeAddressTitle(), safe_form_input()" checked>
                        <label class="btn btn-outline-primary shadow-none" for="btnradio2"><i class="material-icons but-icon">domain</i>В город</label>
                      </div>
                    </div>
                  </div>
                  <div class="row mt-4">
                    <div class="col-md-2"><h5 id = "addressSelectTitle">Куда</h5></div>
                    <div class="col-md-8">
                      <div id = "input_container" class="input-group mb-1">
                        <input id="addressInput" onkeypress="search()" onclick="search()" onchange="safe_form_input()" class="form-control autocomplete" aria-describedby="button-addon2" aria-label="Адрес" name="addressAuto" placeholder="Введите адрес" type="text" required/>
                        <button type="button" class="btn btn-light shadow-none" onclick="clear_input()">
                          <div class="nav__cont">
                          <i class="material-icons nav__icon" style="font-size: 18px;">clear</i>
                        </div></button>
                      </div>
                      <a href="{{ url_for('driver.maps') }}" id="openMapBtn" class="ml-2"> Выбрать на карте</a>
                    </div>
                  </div>
                  <div class="row mt-4">
                    <div class="col-md-2"><h5>Когда</h5></div>
                    <div class="col-md-8">
                      <select id="tripDay" class="form-select form-select-md" onchange="safe_form_input()" name="day" aria-label=".form-select-sm example">
                        <option value="1">Сегодня</option>
                        <option selected value="2">Завтра</option>
                        <option value="3">Послезавтра</option>
                      </select>
                    </div>
                  </div>
                  <div class="row mt-4">
                    <div class="col-md-2"><h5>Во сколько</h5></div>
                    <div class="col-md-8">
                      <input type="text" id="timepicker" class="form-control" name="timeRaw" data-bs-toggle="modal" placeholder='Выберите время' data-bs-target="#timePickerModal" required onkeyup="var yratext=/['\w', '\s']/; if(yratext.test(this.value)) this.value=''">
                      <div class="modal fade" id="timePickerModal" tabindex="-1" aria-labelledby="timePicker" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
                          <div class="modal-dialog modal-dialog-centered ">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <h4 class="modal-title" id="timePicker">Выберите время</h4>
                                      <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button> -->
                                  </div>
                                  <div class="modal-body">
                                      <div class="picker-container" style="max-width: 500px;"></div>
                                  </div>
                                  <div class="modal-footer">
                                    <div style="width: fit-content; margin-left: auto; margin-right: auto;">
                                      <!-- <button type="button" class="btn btn-secondary" style="width:90px" data-bs-dismiss="modal">Отмена</button> -->
                                      <button type="button" onclick="safe_form_input()" class="btn btn-primary shadow-none" style="width:90px" data-bs-dismiss="modal">Ок</button>
                                    </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                  </div>
                  <div class="row mt-4">
                    <div class="col-md-2"><h5>Число пассажиров</h5></div>
                    <div class="col-md-8">
                      <select id="passengersNum" class="form-select form-select-md" name="passengersNum" onchange="safe_form_input()" aria-label=".form-select-sm example">
                        <option value="1">1 пассажир</option>
                        <option selected value="2">2 пассажира</option>
                        <option value="3">3 пассажира</option>
                      </select>
                    </div>
                  </div>
                  <div class="row mt-4">
                    <div class="col-md-2"><h5>Описание поездки</h5></div>
                    <div class="col-md-8">
                      <textarea class="form-control" id="tripDescription" name="tripDescription" rows="3"></textarea>
                    </div>
                  </div>
                </div>
                <div style="text-align: center;">
                  <input type="submit" class="btn btn-primary btn-lg mt-5 mb-5 shadow-none" value="Создать поездку">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}


{% block script %}
  <!-- Блок скрипта для выделения иконки в меню -->
  <script>    
      var link = document.getElementById("drive_link");
      link.classList.add("nav__link--active");
  </script>

  <!-- Логика страницы -->
  <script src="{{ url_for('static', filename='js/picker.js') }}"></script>
  <script src="{{ url_for('static', filename='js/startTripForm.js') }}"></script>
  <script src="{{ url_for('static', filename='js/geosearch.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
{% endblock %}