PodveziSosedaSource/app/ConfirmEmail/controllers.py
from flask import Blueprint, render_template, redirect, url_for, session
from flask_login import login_required, current_user
from itsdangerous import SignatureExpired

from app.models import db, Users, Email_Confirm_Tokens
from app.utils.utils import confirm_required, secure_token


confirmEmail = Blueprint('confirmEmail', __name__, url_prefix ='/confirm_email')


@confirmEmail.route('/<token>')
def confirm_email(token):
    '''Подтверждение адреса email по токену'''
    try:
        user_id = Email_Confirm_Tokens.query.filter(token==token).all()[-1].user_id
        user_email = Users.query.filter(Users.id == user_id).first().email
        if user_email != session["email"]:
            return render_template("Confirm_Email/confirm_email_token.html", text="Токен недействителен", isOk=False)
        Email_Confirm_Tokens.query.filter(token==token).all()[-1].used = True

        secure_token.loads(token, salt='email-confirm', max_age=600) # max_age - время жизни токена в секундах       
        #Здесь делаем запись в бд, что пользователь подвердил адрес
        print("Пользователь подтвердил email " + session["email"])
        Users.query.filter(Users.email == session["email"]).first().confirmed = True
        db.session.flush()
        db.session.commit()
        return redirect(url_for('/profile'))
    except SignatureExpired:
        return render_template("Confirm_Email/confirm_email_token.html", text = "Ваша ссылка истекла, запросите новую", isOk=False)
    except:
        db.session.rollback()
        if "email" not in session:
            return render_template("Confirm_Email/confirm_email_token.html", text="Произошла ошибка, попробуйте позже", isOk=False)
    return render_template("Confirm_Email/confirm_email_token.html", text="Успешно подтвержден адрес:", email=session["email"], isOk=True) 


@confirmEmail.route('/letter')
def confirm_letter():
    '''Информация об отправке письма на почту'''
    email = Users.query.filter(Users.id == current_user.get_id()).first().email
    return render_template("Confirm_Email/confirm_email_letter.html", email=email) #'Вам на почту отправлена ссылка, перейдите по ней, чтобы подтвердить свой адрес электронной почты'


# Представление для отправки письма на почту с подтверждением, если пользователь не подтвержден, используется декоратор, если подтвержден, идет в профиль
@confirmEmail.route("/send_confirm")
@confirm_required
@login_required
def send_confirm():
    '''Ссылка в настройки'''
    return redirect(url_for('settings'))

PodveziSosedaSource/app/Profile/controllers.py
from flask import Blueprint, render_template, url_for, make_response, current_app
from flask_login import login_required, current_user

from app.models import Users, Profiles
from app.utils.utils import confirm_required


profiles = Blueprint('profiles', __name__, url_prefix ='/profile')


# Профиль вошедшего пользователя

@profiles.route("/", methods=["POST", "GET"])
@confirm_required
@login_required
def profile():
    '''Профиль пользователя'''
    user = Users.query.filter(Users.id == current_user.get_id()).first()
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
    return render_template("Profile/profile.html", id=current_user.get_id(), name =f"{user.first_name} {user.second_name}", description=profile.description, email=user.email, 
        phone=user.phoneNum, confirmed=user.confirmed, address=profile.home_address)


@profiles.route('/load_avatar')
@login_required
def load_avatar():
    '''Выгрузка аватара из бд'''
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()

    img = None
    if not profile.photo:
        try:
            with current_app.open_resource(current_app.root_path + url_for('static', filename='imgs/default-ava.png'), "rb") as f:
                img = f.read()
        except FileNotFoundError as e:
                print("Не найден аватар по умолчанию: "+str(e))
    else:
        img = profile.photo

    if not img:
        return ""
    h = make_response(img)
    return h


# Профили остальных пользователей

@profiles.route("/<user_id>")
@login_required
def user(user_id):
    '''Профиль внешнего пользователя'''
    user = Users.query.filter(Users.id == user_id).first_or_404()
    profile = Profiles.query.filter(Profiles.user_id == user_id).first_or_404()
    return render_template("Profile/user.html", id=user_id, name =f"{user.first_name} {user.second_name}", description=profile.description, email=user.email, 
        phone=user.phoneNum, confirmed=user.confirmed, address=profile.home_address)


@profiles.route('/load_user_avatar/<user_id>')
@login_required
def load_user_avatar(user_id):
    '''Выгрузка аватара из бд'''
    profile = Profiles.query.filter(Profiles.user_id == user_id).first_or_404()

    img = None
    if not profile.photo:
        try:
            with current_app.open_resource(current_app.root_path + url_for('static', filename='imgs/default-ava.png'), "rb") as f:
                img = f.read()
        except FileNotFoundError as e:
                print("Не найден аватар по умолчанию: "+str(e))
    else:
        img = profile.photo

    if not img:
        return ""
    h = make_response(img)
    return h

PodveziSosedaSource/app/Settings/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from app.models import db, Users, Profiles
from app.utils.geoloc import get_geocode_gv3, get_geocode_osm


settings_module = Blueprint('settings', __name__, url_prefix ='/settings')



@settings_module.route("/", methods=["POST", "GET"])
@login_required
def settings():
    '''Настройки'''
    user = Users.query.filter(Users.id == current_user.get_id()).first()
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
    return render_template("Settings/settings.html", first_name=user.first_name, second_name=user.second_name, email=user.email,
        phone=user.phoneNum, description=profile.description, address=profile.home_address, search_radius=profile.trip_search_radius, hidden="d-none" if user.confirmed == True else "0")


@settings_module.route('/upload_avatar', methods=["POST", "GET"])
@login_required
def upload():
    '''Загрузка аватара'''
    if request.method == 'POST':
        file = request.files['file']
        if file and current_user.verifyExt(file.filename):
            try:
                img = file.read()
                Profiles.query.filter(Profiles.user_id == current_user.get_id()).first().photo = img
                db.session.commit()

                flash("Аватар обновлен", "success")
            except FileNotFoundError as e:
                flash("Ошибка чтения файла", "error")
        else:
            flash("Ошибка обновления аватара", "error")
 
    return redirect("/settings")


@settings_module.route('/upload_new_password', methods=["POST", "GET"])
@login_required
def upload_new_password():
    '''Изменение пароля'''
    user = Users.query.filter(Users.id == current_user.get_id()).first()
    if request.method == 'POST':
        if len(request.form['new_psw']) > 4:
            if check_password_hash(user.psw, request.form['old_psw']): 
                try:
                    hash = generate_password_hash(request.form['new_psw'])
                    user.psw = hash
                    db.session.commit()
                    flash("Пароль успешно изменен", "success")
                except:
                    db.session.rollback()
                    flash("Ошибка изменения пароля", "error")
            else:
                flash("Пароль неверный", "error")
        else: flash("Новый пароль слишком короткий", "error")
    
    return redirect(url_for('settings.settings'))


@settings_module.route('/upload_basic_info', methods=["POST", "GET"])
@login_required
def upload_basic_info():
    '''Загрузка и обновление информации из профиля'''
    u = Users.query.filter(Users.id == current_user.get_id()).first()

    if request.method == 'POST':
        first_name = request.form["first_name"]
        second_name = request.form["second_name"]
        phone = request.form["phone"]
        email = request.form["email"]
        print(first_name, second_name, phone, email)
        try:
            if (first_name != u.first_name): u.first_name = first_name 
            if (second_name != u.second_name): u.second_name = second_name 
            if (phone != u.phoneNum): u.phoneNum = phone
            if (email != u.email):
                u.email = email
                u.confirmed = False
            db.session.commit()
            flash("Данные сохранены", "success")
            return redirect(url_for('send_confirm'))
        except:
            flash("Ошибка сохранения данных", "error") 

    return redirect("/settings")


@settings_module.route('/upload_description', methods=["POST", "GET"])
@login_required
def upload_desc():
    '''Загрузка описания профиля'''
    if request.method == 'POST':
        desc = request.form["desc"]
        if len(desc) <= 600:
            try:
                Profiles.query.filter(Profiles.user_id == current_user.get_id()).first().description = desc
                db.session.commit()
                flash("Описание обновлено", "success")
            except:
                flash("Ошибка обновления описания", "error")
        else:
            flash("Слишком длинное описание", "error")
 
    return redirect("/settings")


@settings_module.route('/address/confirm', methods=["POST", "GET"])
@login_required
def address_confirm():
    '''Подтверждение гео. адреса'''
    if request.method == 'POST':
        place = request.form["place"]
        #location = get_geocode_gv3(place) # определить адрес, используя Google
        location = get_geocode_osm(place) # определить адрес, используя Nominatim (Свободная лицензия, возможность установить на свой сервер)
        session["place"] = place
        if location:
            return render_template("Settings/address-confirm.html", address=location.address)
        else:
            flash("Вы ввели несуществующий адрес", "error")
 
    return redirect("/settings")


@settings_module.route('/address/upload', methods=["POST", "GET"])
@login_required
def address_upload():
    '''Загрузка гео. адреса'''
    if request.method == 'POST':
        place = session["place"]
        #location = get_geocode_gv3(place) # определить адрес, используя Google
        location = get_geocode_osm(place) # определить адрес, используя Nominatim (Свободная лицензия, возможность установить на свой сервер)
        print("Адрес"+location.address)
        if location:
            try:
                p = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
                p.home_address = location.address
                p.home_latitude = location.latitude
                p.home_longitude = location.longitude
                db.session.commit()
                flash("Адрес загружен", "success")
            except:
                flash("Ошибка загрузки адреса", "error")

            return redirect("/settings")
        else:
            flash("Вы ввели несуществующий адрес, попробуйте указать его точнее", "error")
 
    return redirect("/settings")


@settings_module.route('/radius_change', methods=["POST", "GET"])
@login_required
def radius_change():
    '''Изменение радиуса поиска поездки'''
    if request.method == 'POST':
        radius = float(request.form["radius"])
        if 0.3 <= radius <= 3.0:
            try:
                Profiles.query.filter(Profiles.user_id == current_user.get_id()).first().trip_search_radius = radius
                db.session.commit()
                flash("Радиус поиска поездки изменён", "success")
            except:
                flash("Ошибка обновления радиуса поиска поездки", "error")
        else:
            flash("Некорректный радиус", "error")
 
    return redirect("/settings")

PodveziSosedaSource/app/templates/Settings/address-confirm.html
{% extends 'base.html' %}

{% block content %}
    <h1>Подтверждение адреса</h1>

    <form action="{{ url_for('settings.address_upload') }}" method="POST" class="form-contact">
        <label for="address">Ваш адрес</label>
        <input class="form-control" id="address-field" name="placeField" type="text" placeholder="{{address}}" readonly>
        <a href="{{ url_for('settings.settings') }}" class="btn btn-primary">Нет</a>
        <input type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ConfirmModal" value="Да">
    
        <!-- Модальное окно подтверждения -->
        <div class="modal fade" id="ConfirmModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Подтвердите действие</h5>
                    </div>
                    <div class="modal-body">
                        Вы действительно хотите установить этот адрес в качестве своего домашнего?
                    </div>
                    <div class="modal-footer">
                        <a href="{{ url_for('settings.settings') }}" class="btn btn-secondary">Нет</a>
                        <button type="submit" class="btn btn-primary">Да</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}


{% block script %}
    <!-- Блок скрипта для выделения иконки в меню -->
    <script>    
        var link = document.getElementById("settings_link");
        link.classList.add("nav__link--active");
    </script>
{% endblock %}

PodveziSosedaSource/app/templates/Settings/settings.html
{% extends 'base.html' %}


{% block css_style %}
<link href="{{ url_for('static', filename='css/settings.css')}}" rel="stylesheet">
{% endblock %}


{% block content %}

{% for cat, msg in get_flashed_messages(True) %}
    <!-- <div class="flash {{cat}}">{{msg}}</div> -->

    <div id="toastDiv" class="position-fixed top-30 start-50 translate-middle-x p-3" style="z-index: 12">
      <div id="infoToast" class="toast hide text-white {{cat}} border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
          <strong class="me-auto">Информация</strong>
          <!-- <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button> -->
        </div>
        <div class="toast-body">
          {{msg}}
        </div>
      </div>
    </div>
{% endfor %}




<div class="container light-style flex-grow-1 container-p-y mb-5" style="margin-left: 0px; max-width: 100%;">

  <h2 class="font-weight-bold py-3 mb-4">
    Настройки аккаунта
  </h2>

  <div class="card overflow-hidden shadow-sm rounded-3">


    <div class="row no-gutters row-bordered row-border-light">
      <div class="col-md-3 pt-0">
        <div class="list-group list-group-flush account-settings-links rounded-3">
          <a class="list-group-item list-group-item-action setting-name border border-dark active" data-bs-toggle="list" href="#account-general"> <i class="material-icons but-icon">manage_accounts</i> Основные</a>
          <a class="list-group-item list-group-item-action border border-dark setting-name" data-bs-toggle="list" href="#account-change-password"> <i class="material-icons but-icon">password</i> Смена пароля</a>
          <a class="list-group-item list-group-item-action border border-dark setting-name" data-bs-toggle="list" href="#account-info"> <i class="material-icons but-icon">contacts</i> Информация</a>
        </div>
      </div>


      <div class="col-md-9">
        <div class="tab-content">
          
          
          <div class="tab-pane fade active show" id="account-general">

            <div class="card-body media align-items-center">
              <div class="d-flex flex-row">
                <img src="{{ url_for('profiles.load_avatar') }}" loading="lazy" alt="" class="d-block ui-w-80">
                
                <div class="media-body" style="margin-left: 10px;">
                  <form action="{{ url_for('settings.upload') }}" method="POST" enctype="multipart/form-data">
                    <p>Выберите новую фотографию:</p>
                    <label class="btn btn-secondary btn-sm">
                      Выбрать
                      <input type="file" name="file" class="account-settings-fileinput">
                    </label> &nbsp;
                    <input type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#changeConfirmModal" value="Загрузить">
       
                     <!-- Модальное окно подтверждения -->
                     <div class="modal fade" id="changeConfirmModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Подтвердите действие</h5>
                          </div>
                          <div class="modal-body">
                              Сохранить изменения?
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                          </div>
                        </div>
                      </div>
                     </div>
                  </form> 
                </div>

              </div>
              <div class="text-light small mt-1">Допустимы JPG, PNG. Максимальный размер 1MB</div>
            </div>
            <hr class="border-light m-0">

            <div class="card-body">


              <form action="{{ url_for('settings.upload_basic_info') }}" method="POST" enctype="multipart/form-data">
                
                <div class="form-group">
                  <label class="form-label">Имя</label>
                  <input type="text" name="first_name" class="form-control mb-1" value="{{ first_name }}">
                </div>
  
                <div class="form-group">
                  <label class="form-label">Фамилия</label>
                  <input type="text" name="second_name" class="form-control" value="{{ second_name }}">
                </div>
  
                <div class="form-group">
                  <label class="form-label">Телефон</label>
                  <input type="text" name="phone" class="form-control" value="{{ phone }}">
                </div>
  
                <div class="form-group">
                  <label class="form-label">E-mail</label>
                  <input type="text" name="email" class="form-control mb-1" value="{{ email }}">
                  <div class="alert alert-warning mt-3 {{ hidden }}" >
                    Ваш адрес не подтвержден, чтобы пользоваться сайтом, перейдите по ссылке, отправленной в электронном письме<br>
                    <a href="{{ url_for('confirmEmail.send_confirm') }}">Повторить отправку</a>
                  </div>
                  <input type="button" class="btn btn-primary btn-sm mt-3" data-bs-toggle="modal" data-bs-target="#changeBasicsModal" value="Сохранить изменения">
                </div>
  
                <!-- Модальное окно подтверждения -->
                <div class="modal fade" id="changeBasicsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Подтвердите действие</h5>
                    </div>
                    <div class="modal-body">
                        Сохранить изменения?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                      <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                  </div>
                </div>
                </div>
  
              </form>


            </div>

          </div>
          

          <div class="tab-pane fade" id="account-change-password">
            <div class="card-body pb-2">





              <form action="{{ url_for('settings.upload_new_password') }}" method="POST" enctype="multipart/form-data">

                <div class="form-group">
                  <label class="form-label">Текущий пароль</label>
                  <input type="password" name = "old_psw" class="form-control">
                </div>
  
                <div class="form-group">
                  <label class="form-label">Новый пароль</label>
                  <input type="password" name = "new_psw" class="form-control">
                </div>
                <input type="button" class="btn btn-primary btn-sm mt-3 mb-4" data-bs-toggle="modal" data-bs-target="#changeDescriptionModal" value="Сохранить изменения">
   
                <!-- Модальное окно подтверждения -->
                <div class="modal fade" id="changeDescriptionModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                   <div class="modal-dialog modal-dialog-centered">
                     <div class="modal-content">
                       <div class="modal-header">
                         <h5 class="modal-title" id="exampleModalLabel">Подтвердите действие</h5>
                       </div>
                       <div class="modal-body">
                           Сохранить изменения?
                       </div>
                       <div class="modal-footer">
                         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                         <button type="submit" class="btn btn-primary">Сохранить</button>
                       </div>
                     </div>
                   </div>
                 </div>
              </form> 




            </div>
          </div>


          <div class="tab-pane fade" id="account-info">
            
            <div class="card-body pb-2">
              <h6 class="mb-4">Общая</h6>

              <form action="{{ url_for('settings.upload_desc') }}" method="POST" class="form-outline" enctype="multipart/form-data">
                <div class="form-group">
                  <label class="form-label">Описание</label>
                  <textarea name="desc" class="form-control" id="descArea" rows="5">{% if description %}{{ description }}{% endif %}</textarea>
                </div>
                <!-- <input type="button" class="btn btn-primary btn-sm mt-3 mb-4" data-bs-toggle="modal" data-bs-target="#changeDescriptionModal" value="Сохранить"> -->
                <button type="submit" class="btn btn-sm btn-primary mt-3">Сохранить</button>
                <!-- Модальное окно подтверждения
                <div class="modal fade" id="changeDescriptionModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                   <div class="modal-dialog modal-dialog-centered">
                     <div class="modal-content">
                       <div class="modal-header">
                         <h5 class="modal-title" id="exampleModalLabel">Подтвердите действие</h5>
                       </div>
                       <div class="modal-body">
                           Сохранить изменения?
                       </div>
                       <div class="modal-footer">
                         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                         <button type="submit" class="btn btn-primary">Сохранить</button>
                       </div>
                     </div>
                   </div>
                 </div> -->
              </form> 

            </div>
            
            <hr class="border-light m-0">

            <div class="card-body pb-2">
              <h6 class="mb-4">Геолокация</h6>
              <div class="address_change">
                <form action="{{ url_for('settings.address_confirm') }}" method="POST" class="form-outline" enctype="multipart/form-data">
                  <div class="form-group">
                    <label class="form-label">Домашний адрес</label>
                    <textarea name="place" class="form-control" id="placeArea" rows="1">{% if address %}{{ address }}{% endif %}</textarea>
                  </div>       
                  <input type="submit" class="btn btn-primary btn-primary btn-sm mt-3 mb-4" value="Изменить">
                </form> 
              </div>
            </div>


            <!-- nenenenenneneneneneen -->
            <div class="card-body pb-2">
              <div class="address_change">
                <form action="{{ url_for('settings.radius_change') }}" method="POST" class="form-outline" enctype="multipart/form-data">
                  <div class="form-group">
                    <label class="form-label">Радиус поиска поездок в режиме пассажира (км)</label>
                    <input type="number" step=0.1 min="0.3" max="3.0" name="radius" class="form-control mb-1" value="{{ search_radius }}">
                  </div>       
                  <input type="submit" class="btn btn-primary btn-primary btn-sm mt-3 mb-4" value="Сохранить">
                </form> 
              </div>
            </div>
    
          </div>

        </div>
      </div>
    </div>
  </div>

</div>




{% endblock %}

{% block script %}

    <!-- Блок скрипта для выделения иконки в меню -->
    <script>    
        var link = document.getElementById("settings_link")
        link.classList.add("nav__link--active")
    </script>

    <!-- Тост -->
    <script>
      var option = {
        animation: true,
        delay: 3000
      }
      function showToast() {
        let toastAlert = document.getElementById("infoToast")
        let bsAlert = new bootstrap.Toast(toastAlert, option)
        bsAlert.show()
      }
      window.onload = showToast()
    </script>

    <script>
      // При большом экране изменим раположени тоста
      if (window.innerWidth >= 767) {
        var toastCont = document.getElementById("toastDiv")
        toastCont.classList.remove("start-50", "translate-middle-x")
        toastCont.classList.add("end-0")
      }
    </script>
{% endblock %}