PodveziSosedaSource/app/AuthModule/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import LoginManager, login_user, login_required, current_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash


from app.models import db, Users, Profiles
from app.utils.userLogin import UserLogin


# Подключим модуль авторизации Flask-login
login_manager = LoginManager()
# Перенаправляем неавторизованного пользователя на страницу авторизации при попытке посетить закрытую страницу
login_manager.login_view = 'auth.login'
login_manager.login_message = "Авторизуйтесь для доступа к закрытым страницам"
login_manager.login_message_category = "success"

@login_manager.user_loader
def load_user(user_id):
    return UserLogin().fromDB(user_id, Users)


auth = Blueprint('auth', __name__, url_prefix ='/auth')


@auth.route("/register", methods=("POST", "GET"))
def register():
    '''Регистрация нового пользователя'''
    # Если пользователь уже вошел, он идет в свой профиль
    if current_user.is_authenticated:
        return redirect("/profile")

    if request.method == "POST":
        # Проверка пароля на сложность
        if len(request.form['psw']) < 5:
             flash('Пароль должен быть длиннее пяти символов', category = 'error')
             return render_template("Auth/register.html", title="Регистрация")

        # Создание нового пользователя
        try:
            hash = generate_password_hash(request.form['psw'])
            email = request.form['email']

            u = Users(email=email, psw=hash, first_name=request.form['first_name'], second_name=request.form['second_name'],
                phoneNum=request.form['phoneNum'])
            db.session.add(u)
            db.session.flush()

            p = Profiles(user_id = u.id)
            db.session.add(p)
            db.session.commit()

            print("Данные внесены в бд")

            # Осуществляем логин пользователя
            user = Users.query.filter(Users.email == email).first()
            if user:
                userlogin = UserLogin().create(user)
                login_user(userlogin, remember=True)
            print("Вход в аккаунт выполнен")

            return redirect(url_for('confirmEmail.send_confirm'))
        except Exception as exc:
            print(exc)
            db.session.rollback()
            flash('Не удалось зарегистрироваться', category = 'error')
            print("Ошибка добавления в БД")

    return render_template("Auth/register.html", title="Регистрация")


@auth.route("/login", methods=["POST", "GET"])
def login():
    '''Логин пользователя'''
    # Если пользователь уже вошел, он идет в свой профиль
    if current_user.is_authenticated:
        return redirect("/profile")

    if request.method == "POST":
        user = Users.query.filter(Users.email == request.form['email']).first()
        if user and check_password_hash(user.psw, request.form['psw']):
            userlogin = UserLogin().create(user)
            rm = True if request.form.get('remainme') else False # Запоминать пользователя или нет
            login_user(userlogin, remember=rm)
            return redirect(request.args.get("next") or "/profile")

        flash("Неверная пара логин/пароль", "error")
 
    return render_template("Auth/login.html", title="Авторизация")


@auth.route('/logout')
@login_required
def logout():
    '''Выход из аккаунта'''
    logout_user()
    flash("Вы вышли из аккаунта", "success")
    return redirect(url_for('.login'))

PodveziSosedaSource/app/Profile/controllers.py
from flask import Blueprint, render_template, url_for, make_response, current_app
from flask_login import login_required, current_user

from app.models import Users, Profiles
from app.utils.utils import confirm_required


profiles = Blueprint('profiles', __name__, url_prefix ='/profile')


# Профиль вошедшего пользователя

@profiles.route("/", methods=["POST", "GET"])
@confirm_required
@login_required
def profile():
    '''Профиль пользователя'''
    user = Users.query.filter(Users.id == current_user.get_id()).first()
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()
    return render_template("Profile/profile.html", id=current_user.get_id(), name =f"{user.first_name} {user.second_name}", description=profile.description, email=user.email, 
        phone=user.phoneNum, confirmed=user.confirmed, address=profile.home_address)


@profiles.route('/load_avatar')
@login_required
def load_avatar():
    '''Выгрузка аватара из бд'''
    profile = Profiles.query.filter(Profiles.user_id == current_user.get_id()).first()

    img = None
    if not profile.photo:
        try:
            with current_app.open_resource(current_app.root_path + url_for('static', filename='imgs/default-ava.png'), "rb") as f:
                img = f.read()
        except FileNotFoundError as e:
                print("Не найден аватар по умолчанию: "+str(e))
    else:
        img = profile.photo

    if not img:
        return ""
    h = make_response(img)
    return h


# Профили остальных пользователей

@profiles.route("/<user_id>")
@login_required
def user(user_id):
    '''Профиль внешнего пользователя'''
    user = Users.query.filter(Users.id == user_id).first_or_404()
    profile = Profiles.query.filter(Profiles.user_id == user_id).first_or_404()
    return render_template("Profile/user.html", id=user_id, name =f"{user.first_name} {user.second_name}", description=profile.description, email=user.email, 
        phone=user.phoneNum, confirmed=user.confirmed, address=profile.home_address)


@profiles.route('/load_user_avatar/<user_id>')
@login_required
def load_user_avatar(user_id):
    '''Выгрузка аватара из бд'''
    profile = Profiles.query.filter(Profiles.user_id == user_id).first_or_404()

    img = None
    if not profile.photo:
        try:
            with current_app.open_resource(current_app.root_path + url_for('static', filename='imgs/default-ava.png'), "rb") as f:
                img = f.read()
        except FileNotFoundError as e:
                print("Не найден аватар по умолчанию: "+str(e))
    else:
        img = profile.photo

    if not img:
        return ""
    h = make_response(img)
    return h

PodveziSosedaSource/app/templates/Profile/profile.html
{% extends 'base.html' %}

{% block css_style %}
<link href="{{ url_for('static', filename='css/profile.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="content">
        <div class = "ava-desc">
            <div class="avatar-block">
                <img src="{{ url_for('profiles.load_avatar') }}" loading="lazy" id = "avatar" class="img-thumbnail rounded"/>
                <h2>{{ name }}</h2>
            </div>
            <div class="description">
                <span id="Description" class = "infType">Описание: </span>
                <p id="Description-text">
                    {% if not description %}
					<span class="nav__cont">
						<a href="{{ url_for('settings.settings') }}" class="btn btn-secondary"><i class="material-icons but-icon">post_add</i>Добавьте</a>
					</span>
					{% else %}
                        {{ description }}
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="info-block">
            <div class="block-with-btn">
                <p><span class = "infType">id: </span>{{ id }}</p>
                <span id = "settings-btn"><a href="{{ url_for('settings.settings') }}"><i class="material-icons nav__icon">settings</i></a></span>
            </div>
            <p><span class = "infType">Email: </span>{{ email }}</p>
            <p><span class = "infType">Телефон: </span>{{ phone }}</p>
            <!-- <p><span class = "infType">Подтвержден: </span>{{ confirmed }}</p> -->
            <p><span class = "infType">Домашний адрес: </span>
                {% if not address %}
                    <a href="{{ url_for('settings.settings') }}" class="btn btn-link">Добавьте</a>
                {% else %}
                    {{ address }}
                {% endif %}
            </p>
        </div>
        <span id = "logout-btn" class="nav__cont" >
			<a href="{{ url_for('auth.logout') }}" class="btn btn-light"><i class="material-icons but-icon">logout</i>Выйти из профиля</a>
		</span>
        <br>
    </div>
{% endblock %}

{% block script %}
    <!-- Блок скрипта для выделения иконки в меню -->
    <script>    
        var link = document.getElementById("profile_link");
        link.classList.add("nav__link--active");
    </script>
{% endblock %}

PodveziSosedaSource/app/templates/Profile/user.html
{% extends 'base.html' %}

{% block css_style %}
<link href="{{ url_for('static', filename='css/profile.css')}}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/swupy.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="swup" class="content transition-fade">
        <div class = "ava-desc">
            <div class="avatar-block">
                <img src="{{ url_for('profiles.load_user_avatar', user_id=id) }}" id = "avatar" class="img-thumbnail rounded" />
                <h2>{{ name }}</h2>
                <!-- <button type="button" class="btn btn-light btn-rounded m-3"><i class="material-icons nav__icon mr-1 pd-0 fs-6" style="padding: 7px 6px;">chat</i>Написать</button> -->
            </div>
            <div class="description">
                <span id="Description" class = "infType">Описание: </span>
                <p id="Description-text">
                    {% if not description %}
                        <p class="text-muted">Пользователь не добавил описание</p>
                    {% else %}
                        {{ description }}
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="info-block">
            <div class="block-with-btn">
                <p><span class = "infType">id: </span>{{ id }}</p>
            </div>
            <p><span class = "infType">Email: </span>{{ email }}</p>
            <p><span class = "infType">Телефон: </span>{{ phone }}</p>
            <!-- <p><span class = "infType">Подтвержден: </span>{{ confirmed }}</p> -->
            <p><span class = "infType">Домашний адрес: </span>
                {% if not address %}
                <p class="text-muted">Пользователь не добавил адрес</p>
                {% else %}
                    {{ address }}
                {% endif %}
            </p>
        </div>
    </div>
{% endblock %}

{% block script %}
    <!-- Блок скрипта для выделения иконки в меню -->
    <script>    
        var link = document.getElementById("profile_link");
        link.classList.add("nav__link--active");
    </script>

    <!-- Swup - плавные переходы -->
    <script src="{{ url_for('static', filename='js/swup.min.js')}}"></script>
    <script>const swup = new Swup();</script>
{% endblock %}